# NumPy

In [1]:
import numpy as np
np.__version__

'1.15.3'

## 关于区间

* 区间表示[x1, x2] **包括x2**
* 区间表示[x1, x2) **不包括x2**

## 主要的数据结构
* ndarray（N-dimensional array object)，解决了多维数组的问题。
* ufunc（universal function object)，对数组进行处理的函数。

### ndarray

在 NumPy 数组中，维数称为秩（rank），一维数组的秩为 1，二维数组的秩为 2，以此类推。每一个线性的数组称为一个轴（axes），其实秩就是描述轴的数量。

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

* shape 形状

In [4]:
print(a.shape)
print(b.shape)

(3,)
(3, 3)


* dtype 类型

In [7]:
a.dtype

dtype('int64')

* 索引 [行, 列]

In [8]:
b[1, 1]=10
b

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [9]:
b[:, 1]

array([ 2, 10,  8])

In [10]:
b[:2, 1:]

array([[ 2,  3],
       [10,  6]])

In [12]:
b[:]

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

## 数组的创建

* np.arange() 在区间[1,10)中按间隔2取数

In [18]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

* np.linspace() 在区间[1,9]中取出5个数

In [23]:
np.linspace(1, 9, 5)

array([1., 3., 5., 7., 9.])

* np.random.randn() 随机生成任意维度的数组

In [28]:
np.random.randn(3)

array([-0.23438687, -1.64379021,  1.60173504])

In [29]:
np.random.randn(3, 3)

array([[ 0.65966311, -2.23857093,  1.02629538],
       [ 1.23443881,  0.14581205,  0.73402549],
       [-0.68821167, -0.16400579,  0.55171236]])

In [30]:
np.random.randn(3, 3, 3)

array([[[-1.80909812,  1.10548106,  0.00907181],
        [-0.83908552, -0.45071946, -0.46633056],
        [ 0.4820896 , -0.01023019, -1.36290676]],

       [[ 0.61727905,  0.96843408,  0.77933994],
        [-0.96357387,  0.9087393 ,  0.96271833],
        [-0.14304401, -1.60002223, -1.05155362]],

       [[ 0.62934759, -0.6269761 , -0.69716794],
        [-0.95512112, -0.91051672,  0.36352296],
        [-0.22627551,  0.66666617, -0.8870291 ]]])

* np.random.rand() 生成0-1的均匀分布的随机数

In [68]:
np.random.rand()

0.6063503849965021

In [69]:
np.random.rand(3)

array([0.16396061, 0.76651519, 0.02427173])

In [70]:
np.random.rand(3, 3)

array([[0.79490967, 0.028347  , 0.5561012 ],
       [0.35609771, 0.97141822, 0.23844782],
       [0.63649398, 0.67192737, 0.04413091]])

## 算术运算

In [35]:
x1 = np.arange(1, 10, 2)
x2 = np.linspace(1, 9, 5)

print(x1, x2)

[1 3 5 7 9] [1. 3. 5. 7. 9.]


In [40]:
#加
np.add(x1, x2)

array([ 2.,  6., 10., 14., 18.])

In [41]:
#减
np.subtract(x1, x2)

array([0., 0., 0., 0., 0.])

In [42]:
#乘
np.multiply(x1, x2)

array([ 1.,  9., 25., 49., 81.])

In [43]:
#除
np.divide(x1, x2)

array([1., 1., 1., 1., 1.])

In [44]:
#n次方
np.power(x1, x2)

array([1.00000000e+00, 2.70000000e+01, 3.12500000e+03, 8.23543000e+05,
       3.87420489e+08])

In [46]:
#求yu
np.remainder(x1, x2)
np.mod(x1, x2)

array([0., 0., 0., 0., 0.])

## 统计函数

In [47]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* min 最小值。第2个参数是轴。**0是跨行，纵向。1是跨列，横向。**

In [53]:
np.min(n)

1

In [54]:
np.min(n, 0)

array([1, 2, 3])

In [55]:
np.min(n, 1)

array([1, 4, 7])

* max 最大值

In [61]:
np.max(n)

9

In [62]:
np.max(n, 0)

array([7, 8, 9])

In [63]:
np.max(n, 1)

array([3, 6, 9])

## 参考资料
* [NumPy Manual](https://numpy.org/devdocs/index.html)
* [Numpy 中文文档](https://www.numpy.org.cn/article/basics/understanding_numpy.html)
* [Numpy Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html)
* [Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/)